name: connectme
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - backend-network
    restart: always
    volumes:
      - log-data:/app/log
    depends_on:
      - db
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/data/logs
    depends_on:
      - backend
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://caddy:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PORT=${DATABASE_PORT}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:latest
    env_file:
      - .env
    container_name: cache
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    volumes:
      - cache-data:/data
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
  log-data:
  cache-data:
  caddy-config:
  caddy-data:
  caddy-logs:
